import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

import { Sidebar } from "@/components/layout/sidebar";
import { Topbar } from "@/components/layout/topbar";

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased dark`}
    >
      <head>
        <script dangerouslySetInnerHTML={{ __html: `
          if (typeof window !== 'undefined') {
            const originalFetch = window.fetch;
            window.fetch = function (input, init) {
              if (typeof input === 'string' && (input.includes('.loca.lt') || input.includes('localhost') || input.includes('127.0.0.1'))) {
                init = init || {};
                init.headers = init.headers || {};
                if (init.headers instanceof Headers) {
                  init.headers.set('bypass-tunnel-reminder', 'true');
                } else if (Array.isArray(init.headers)) {
                  init.headers.push(['bypass-tunnel-reminder', 'true']);
                } else {
                  init.headers['bypass-tunnel-reminder'] = 'true';
                }
              }
              return originalFetch.call(this, input, init);
            };
          }
        ` }} />
      </head>
      <body className="flex h-full min-h-screen bg-white text-zinc-950 dark:bg-black dark:text-zinc-50">
        <Sidebar className="hidden md:flex" />
        <div className="flex flex-1 flex-col overflow-hidden">
          <Topbar />
          <main className="flex-1 overflow-y-auto p-6 bg-zinc-50 dark:bg-zinc-950">
            {children}
          </main>
        </div>
      </body>
    </html>
  );
}
